### ISSUE TITLE
Add functionality check helper

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/Metal.jl#121]
Something simple like https://github.com/JuliaGPU/oneAPI.jl/blob/652a93df628d0e26f3f6fa96235eeae102dc572c/lib/level-zero/oneL0.jl#L81-L107

**Comment by christiangnrd** [comment]
I've been looking at how to implement this and I'm probably overthinking it. Would a function that basically does the same thing as the check in [2baf6dc](https://github.com/JuliaGPU/Metal.jl/commit/2baf6dc6edb53beb54d969b8f8efd94346ef4585) be sufficient?

I took a shot at implementing [MTLGPUFamily](https://developer.apple.com/documentation/metal/mtlgpufamily?language=objc). I don't think it could be used for this since it returned true for metal3 on an Intel HD 630 (definitely broken), but I can create a separate PR if it would be useful.

**Comment by maleadt** [comment]
> Would a function that basically does the same thing as the check in [2baf6dc](https://github.com/JuliaGPU/Metal.jl/commit/2baf6dc6edb53beb54d969b8f8efd94346ef4585) be sufficient?

I wouldn't even bother validating devices, but just that the package is loadable. That involves being able to call the Metal APIs, for which the proxy currently is a simple `Sys.isapple()` check: https://github.com/JuliaGPU/Metal.jl/blob/41c6018fa27c54559813a074b3b9a4f11516466a/src/initialization.jl#L5-L8.

The device check we only do when activating a device, and yes it might be good to use proper APIs there instead of string-matching the name. Can you not check for `MTLGPUFamilyApple*` to make that actually work?

**Comment by christiangnrd** [comment]
> Can you not check for `MTLGPUFamilyApple*` to make that actually work?

`MTLGPUFamilyApple7` is for A14 and M1 but it also returns `true` on my M2 so I believe it could work as a validator fo devices.

As for the topic of this issue, would any call to the metal API in a try/catch block do the job?

**Comment by maleadt** [comment]
> As for the topic of this issue, would any call to the metal API in a try/catch block do the job?

Yeah sure. For something useful, maybe a version check that generates a `@debug` message? We don't want to do _actual_ work during `__init__`.
