### ISSUE TITLE
Two suspicious `mtl`-related behaviours

### ISSUE THREAD

**Issue by christiangnrd** [JuliaGPU/Metal.jl#289]
Is this intended behaviour?

1. `mtl[]` does not seem to adapt datatypes like `mtl([])` does
2. `mtl(Float16[])` does not promote up to Float32 but `mtl(ComplexF16[])` promotes up to ComplexF32

I'm not sure if these are intended behaviours, but 1 seems very unintuitive to me. I don't see complex numbers so there might be a justification for the difference in behaviour between real and complex numbers of 2.

Both of these are present in CUDA so I can file an (or separate) issue(s) there if these are not intended.

Ex for 1:
```
julia> mtl([0.9])
1-element MtlVector{Float32, Metal.MTL.MTLResourceStorageModePrivate}:
 0.9

julia> mtl[0.9]
ERROR: Metal does not support Float64 values, try using Float32 instead
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] check_eltype(T::Type)
   @ Metal ~/.julia/packages/Metal/OchAS/src/array.jl:32
 [3] MtlVector{Float64, Metal.MTL.MTLResourceStorageModePrivate}(::UndefInitializer, dims::Tuple{Int64})
   @ Metal ~/.julia/packages/Metal/OchAS/src/array.jl:50
 [4] (MtlVector{Float64})(::UndefInitializer, dims::Tuple{Int64})
   @ Metal ~/.julia/packages/Metal/OchAS/src/array.jl:100
 [5] MtlArray
   @ ~/.julia/packages/Metal/OchAS/src/array.jl:159 [inlined]
 [6] MtlArray(A::Vector{Float64})
   @ Metal ~/.julia/packages/Metal/OchAS/src/array.jl:175
 [7] getindex(::typeof(mtl), xs::Float64)
   @ Metal ~/.julia/packages/Metal/OchAS/src/array.jl:382
 [8] top-level scope
   @ REPL[8]:1
 [9] top-level scope
   @ ~/.julia/packages/Metal/OchAS/src/initialization.jl:57
```

Ex for 2:
```
julia> mtl([Float16(0.9)])
1-element MtlVector{Float16, Metal.MTL.MTLResourceStorageModePrivate}:
 0.9

julia> mtl([ComplexF16(0.9)])
1-element MtlVector{ComplexF32, Metal.MTL.MTLResourceStorageModePrivate}:
 0.89990234f0 + 0.0f0im
```

**Comment by maleadt** [comment]
> `mtl[]` does not seem to adapt datatypes like `mtl([])` does

This functionality is terrible and should be removed. `mtl` is a function, `mtl[...]` is a horrible pun. I forgot I had ported that over from CUDA.jl, where IIRC I've removed it since.

**Comment by christiangnrd** [comment]
I'm the one that ported it in #194. I probably noticed it didn't behave like CUDA and took the opportunity to "fix" it. My apologies. What about the second thing? If it's intended I'll repurpose the pull request to remove `mtl[...]` only.

**Comment by maleadt** [comment]
Ah, I see. Unless you feel strongly, I would vote for removing it again (even though that would be a breaking change, so we should verify nobody is relying on it). It's IMO not a good API.



> `mtl(Float16[])` does not promote up to Float32 but `mtl(ComplexF16[])` promotes up to ComplexF32

Yeah that seems wrong, neither should promote. I guess the same bug will exist in CUDA.jl as well, and I wonder if we shouldn't just restrict the scope of the promotion to only Float64->Float32 and the complex equivalents (so that it doesn't cover Float16 and whatever we add in the future): https://github.com/JuliaGPU/CUDA.jl/blob/7a9a0a2a6becc4fba27fc664d1051194037a41e6/src/array.jl#L737-L748

**Comment by christiangnrd** [comment]
> Ah, I see. Unless you feel strongly, I would vote for removing it again (even though that would be a breaking change, so we should verify nobody is relying on it). It's IMO not a good API.

Not at all. I've updated the PR to remove it.
 

> I wonder if we shouldn't just restrict the scope of the promotion to only Float64->Float32 and the complex equivalents (so that it doesn't cover Float16 and whatever we add in the future)

Float16 promotion is explicitly covered here. Would explicitly preventing promotion on the supported types and then defaulting to promoting to Float64 for any other AbstractFloat be better? That way types like BigFloat also get converted to Float32.

**Comment by maleadt** [comment]
> That way types like BigFloat also get converted to Float32.

I know it behaves like that right now, but I'm not sure that's great. Generally, we're pretty strict wrt. (dis)allowing types in GPU kernels, so transparently supporting BigFloat when working with arrays (and losing a bunch of precision because of that conversion) seems questionable to me. The exception has been Float64->Float32 because of the massive performance difference on consumer hardware.

**Comment by christiangnrd** [comment]
For now I think a decent solution would be to add Int128/UInt128 to check_eltype and then make adapt_storage specific to Float64 which would have the (intended) side-effect of BigFloat erroring for not being stored inline.
