### ISSUE TITLE
Super slow broadcast

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaGPU/Metal.jl#39]
Hi, the following MWE evaluates the observed bandwidth for a **broadcasted** copy of two Metal vector of Float32.
It returns a value of 0.05 GBs on my machine (M1 Max with 64Go) while I observe 350 GBs for the kernel copy...

```
using Metal

function slow_broadcast(n=2^20,nsample=10)

    a = MtlArray(rand(Float32, n))
    b = MtlArray(rand(Float32, n))

    nsample = 10
    ts=zeros(nsample)
    for i ∈ 1:nsample
        ts[i] = @elapsed Metal.@sync begin
            a .= b
        end
    end
    @show ts
    tmin = minimum(ts)

    size_in_bytes = 2n*sizeof(Float32) #1R+1W
    byte_per_ns = size_in_bytes / (tmin*1.e9)

    println("GBs: $(round(byte_per_ns; digits=4))")

    # Cleanup memory (is it necessary ?)
    finalize(a)
    finalize(b)
end

slow_broadcast()
```

**Comment by maxwindiff** [comment]
It's because the heuristics for broadcast kernel are not calculated correctly. [GPUArrays.jl](https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/host/broadcast.jl#L72) passes `elements_per_thread=typemax(Int)`. Right now [Metal.jl](https://github.com/JuliaGPU/Metal.jl/blob/main/src/gpuarrays.jl#L17) simply divides the number of elements by `elements_per_thread` to get `threads_needed`, which ends up always setting threads=1.
