### ISSUE TITLE
[MacOS:] `Metal.functional()` wrongly returns true despite no GPUs available

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/Metal.jl#458]
The following tests were executed and failed because `Metal.functional()` returned true:
https://github.com/omlins/CellArrays.jl/actions/runs/11330323307/job/31507893740#step:6:564

**Comment by omlins** [comment]
@christiangnrd this is an issue somewhat similar to #453

**Comment by christiangnrd** [comment]
Thank you for taking the time to report these!

I'm not exactly sure what the best way to resolve this is.

We could enforce `MTLGPUFamilyApple7` and `MTLGPUFamilyMetal3` support through `functional()`, or we could add a new function like `fully_supported()` or something that only returns `true` if the device's GPU has the above support.

@maleadt @tgymnich Any thoughts?

**Comment by maleadt** [comment]
> We could enforce `MTLGPUFamilyApple7` and `MTLGPUFamilyMetal3` support through `functional()`,

I think that would be the best option. Since we automatically select a device, without the user having to check if one is available and select it, it's fair to assume that code using said implicit device works after checking `Metal.functional()`.

In CUDA.jl this is automatic, because the driver fails to initialize if no devices are available.
